POST http://localhost:{{port}}/api/usuarios
Content-Type: application/json

{"id":null,"usuario": "{{username}}","clave":"{{password}}","roles": ["{{roles}}"]}

###

POST http://localhost:{{port}}/api/tokens
Content-Type: application/json

{
  "usuario": "{{username}}",
  "clave": "{{password}}"
}
> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("token_id", response.body.id);
%}
###


GET http://localhost:{{port}}/api/usuarios/{{username}}
Authorization: Bearer {{auth_token}}
Accept: application/json

###

GET http://localhost:{{port}}/api/usuarios
Authorization: Bearer {{auth_token}}
Accept: application/json

###

GET http://localhost:{{port}}/api/usuarios?rol=admin
Authorization: Bearer {{auth_token}}
Accept: application/json

###

GET http://localhost:{{port}}/api/usuarios?usuario={{username}}
Authorization: Bearer {{auth_token}}
Accept: application/json

###

GET http://localhost:{{port}}/api/tokens
Authorization: Bearer {{auth_token}}
Accept: application/json

###

DELETE http://localhost:{{port}}/api/usuarios/{{username}}
Authorization: Bearer {{auth_token}}
Accept: application/json

###

GET http://localhost:{{port}}/api/tokens/{{token_id}}
Authorization: Bearer {{auth_token}}
Accept: application/json

###

DELETE http://localhost:{{port}}/api/tokens/{{token_id}}
Authorization: Bearer {{auth_token}}
Accept: application/json

###