openapi: 3.0.0
info:
  title: Deployed Resources
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Default Server.
paths:
  /api/tokens:
    get:
      operationId: list
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Token'
          description: Default Response.
    post:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credential'
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
          description: Default Response.
  /api/tokens/{token}:
    get:
      operationId: check
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
          description: Default Response.
    delete:
      operationId: delete
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses:
        default:
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
          description: Default Response.
endpoints:
  /:
    - /api/hello
    - /api/tokens
    - "/api/tokens/{token}"
components:
  schemas:
    Credential:
      type: object
      example:
        usuario: pedro
        clave:  pedro
      properties:
        usuario:
          type: string
        clave:
          type: string
    Token:
      type: object
      properties:
        token:
          type: string
        vigencia:
          type: object
        usuario:
          type: string